[tool.poetry]
name = "anki-card-gen"
version = "0.1.0"
description = ""
authors = ["Nick Garvey <garvey.nick@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
